#pragma once

// ============================================================================
// WorldOpcode — Cataclysm 4.3.4 (build 15595) world server opcodes
//
// Only the authentication handshake opcodes are defined here.
// TODO: Complete opcode table for Cata 4.3.4
// ============================================================================

#include <cstdint>

#include <Utils/Describe.hpp>

namespace Fireland::World
{
// ---- Cata 4.3.4 connection initialization strings -------------------------
static const std::string SERVER_CONNECTION_INIT = "WORLD OF WARCRAFT CONNECTION - SERVER TO CLIENT";
static const std::string CLIENT_CONNECTION_INIT = "WORLD OF WARCRAFT CONNECTION - CLIENT TO SERVER";

// Server → Client opcodes (2-byte opcode in header)
enum WorldServerOpcodes : uint32_t
{
    SMSG_AUTH_CHALLENGE = 0x4542,
    CMSG_AUTH_SESSION = 0x0449,
    SMSG_AUTH_RESPONSE = 0x5DB6,
    SMSG_ADDON_INFO = 0x2C14,
    SMSG_CLIENTCACHE_VERSION = 0x2734,
    SMSG_TUTORIAL_FLAGS = 0x0B35,
    SMSG_FEATURE_SYSTEM_STATUS = 0x3DB7,
    SMSG_SET_TIME_ZONE_INFORMATION = 0x38B4,

    CMSG_CHAR_ENUM = 0x0502,
    SMSG_CHAR_ENUM = 0x10B0,
    CMSG_CHAR_CREATE = 0x4A36,
    SMSG_CHAR_CREATE = 0x2D05,
    CMSG_CHAR_DELETE = 0x6425,
    SMSG_CHAR_DELETE = 0x0304,
    CMSG_PLAYER_LOGIN = 0x05B1,
    SMSG_LOGIN_VERIFY_WORLD = 0x2005,
    SMSG_TIME_SYNC_REQ = 0x3CA4,
    SMSG_INITIAL_SPELLS = 0x0104,
    SMSG_ACTION_BUTTONS = 0x38B5,
    SMSG_UPDATE_OBJECT = 0x4715,
    SMSG_MOTD = 0x0A35,
    SMSG_ACCOUNT_DATA_TIMES = 0x4B05,
    SMSG_REALM_SPLIT = 0x2714,
    SMSG_LOGIN_SET_TIME_SPEED = 0x4D15,
    SMSG_LEARNED_DANCE_MOVES = 0x0327,
    SMSG_ACCOUNT_RESTRICTED_UPDATE = 0x2C15,
    SMSG_SET_DF_FAST_LAUNCH_RESOURCES = 0x6D45,
    SMSG_PONG = 0x4D42,
    SMSG_INITIAL_RAID_GROUP_ERROR = 0x19B4,

    CMSG_PING = 0x444D,

    MSG_MOVE_HEARTBEAT = 0x3914,
    MSG_MOVE_START_FORWARD = 0x7814,
    MSG_MOVE_START_BACKWARD = 0x330A,
    MSG_MOVE_STOP = 0x320A,
    MSG_MOVE_SET_FACING = 0x7914,

    CMSG_MESSAGECHAT = 0x1154,
    SMSG_MESSAGECHAT = 0x2026,

    CMSG_READY_FOR_ACCOUNT_DATA_TIMES = 0x2B16,
    CMSG_LOG_DISCONNECT = 0x446D,
};
BOOST_DESCRIBE_ENUM(WorldServerOpcodes,
    SMSG_AUTH_CHALLENGE,
    CMSG_AUTH_SESSION,
    SMSG_AUTH_RESPONSE,
    SMSG_ADDON_INFO,
    SMSG_CLIENTCACHE_VERSION,
    SMSG_TUTORIAL_FLAGS,
    SMSG_FEATURE_SYSTEM_STATUS,
    SMSG_SET_TIME_ZONE_INFORMATION,

    CMSG_CHAR_ENUM,
    SMSG_CHAR_ENUM,
    CMSG_CHAR_CREATE,
    SMSG_CHAR_CREATE,
    CMSG_CHAR_DELETE,
    SMSG_CHAR_DELETE,
    CMSG_PLAYER_LOGIN,
    SMSG_LOGIN_VERIFY_WORLD,
    SMSG_TIME_SYNC_REQ,
    SMSG_INITIAL_SPELLS,
    SMSG_ACTION_BUTTONS,
    SMSG_UPDATE_OBJECT,
    SMSG_MOTD,
    SMSG_ACCOUNT_DATA_TIMES,
    SMSG_REALM_SPLIT,
    SMSG_LOGIN_SET_TIME_SPEED,
    SMSG_LEARNED_DANCE_MOVES,
    SMSG_ACCOUNT_RESTRICTED_UPDATE,
    SMSG_SET_DF_FAST_LAUNCH_RESOURCES,
    SMSG_PONG,
    SMSG_INITIAL_RAID_GROUP_ERROR,

    CMSG_PING,

    MSG_MOVE_HEARTBEAT,
    MSG_MOVE_START_FORWARD,
    MSG_MOVE_START_BACKWARD,
    MSG_MOVE_STOP,
    MSG_MOVE_SET_FACING,

    CMSG_MESSAGECHAT,
    SMSG_MESSAGECHAT,

    CMSG_READY_FOR_ACCOUNT_DATA_TIMES,
    CMSG_LOG_DISCONNECT);

// Expansion constant
constexpr uint8_t EXPANSION_CATACLYSM = 3;

// Cataclysm expected build number
constexpr uint16_t EXPECTED_BUILD = 15595;

// ---- Auth response result codes (used in SMSG_AUTH_RESPONSE) ---------------

enum class AuthResponseResult : uint8_t
{
    AUTH_OK                  = 0x0C,
    AUTH_FAILED              = 0x01,
    AUTH_REJECT              = 0x0E,
    AUTH_BAD_SERVER_PROOF    = 0x02,
    AUTH_UNAVAILABLE         = 0x03,
    AUTH_SYSTEM_ERROR        = 0x04,
    AUTH_BILLING_ERROR       = 0x05,
    AUTH_BILLING_EXPIRED     = 0x06,
    AUTH_VERSION_MISMATCH    = 0x07,
    AUTH_UNKNOWN_ACCOUNT     = 0x08,
    AUTH_INCORRECT_PASSWORD  = 0x09,
    AUTH_SESSION_EXPIRED     = 0x0A,
    AUTH_SERVER_SHUTTING_DOWN = 0x0B,
    AUTH_WAIT_QUEUE          = 0x1B,
};
BOOST_DESCRIBE_ENUM(AuthResponseResult,
    AUTH_OK,
    AUTH_FAILED,
    AUTH_REJECT,
    AUTH_BAD_SERVER_PROOF,
    AUTH_UNAVAILABLE,
    AUTH_SYSTEM_ERROR,
    AUTH_BILLING_ERROR,
    AUTH_BILLING_EXPIRED,
    AUTH_VERSION_MISMATCH,
    AUTH_UNKNOWN_ACCOUNT,
    AUTH_INCORRECT_PASSWORD,
    AUTH_SESSION_EXPIRED,
    AUTH_SERVER_SHUTTING_DOWN,
    AUTH_WAIT_QUEUE);


} // namespace Fireland::World
